<%
distrib, infos    = ENV.fetch('DISTRIB', 'debian:stretch/9').split(':')
codename, version = infos.split('/')
%>
---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: salt_solo
  formula: vim

  # Install Salt from official repositories
  salt_install: apt
  salt_version: latest
  salt_apt_repo: https://repo.saltstack.com/apt/<%= distrib %>/<%= version %>/amd64
  salt_apt_repo_key: https://repo.saltstack.com/apt/<%= distrib %>/<%= version %>/amd64/latest/SALTSTACK-GPG-KEY.pub

  # Don't install Chef
  require_chef: false

  # Configure Salt
  state_top:
    base:
      '*':
        - vim

  pillars:
    top.sls:
      base:
        '*':
          - vim
    vim.sls:
      vim:
        managed_vimrc: true
        config:
          syntax: 'on'
        settings:
          number:

platforms:
  - name: <%= distrib %>-<%= codename %>
    driver_config:
      image: "<%= distrib %>:<%= codename %>"
      platform: <%= distrib %>

verifier:
  name: inspec
  format: progress

suites:
  - name: vim
